
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: glasses-store
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  dbdata:
    driver: local
  cache:
    driver: local
